### ISSUE TITLE
Standards on the Information page

### ISSUE THREAD

**Issue by ClareHorner** [NHSDigital/governance#48]
on the information page at the bottom https://architecture.digital.nhs.uk/information  there's a box about Standards entitled "I want to find information about Technology Standards"

and it says "please refer to the current Standards on the EA Portal"

so that needs to change to Aalto

Also the link (in the title) taks you to an approved technologies list in Aalto that doesn't seem to take you to any page in Aalto about standards???

**Comment by sinclr4** [comment]
Done
