### ISSUE TITLE
Intro text - Home page

### ISSUE THREAD

**Issue by sinclr4** [NHSDigital/governance#8]
The intro text on here: https://architecture-service-manual-staging.azurewebsites.net/ 
The role of the TRG is to provide technical reviews and governance across the delivery lifecycle of all NHS Digital projects. We ensure that the right criteria are being met (principles, strategies, policies, standards and guidance) at every step of the way from Discovery stage to Go Live.

Doesn't really introduce the point of the site,. The original text: "Helping technical architects and project professionals to navigate our technical governance process." seems close to the mark?

**Comment by BigEdDev** [comment]
@sinclr4  this was updated to _Helping architects, app / service designers and project professionals and leads to navigate our technical governance process._

I will forward this on so the content editors are aware this was raised to see if they need to make any new amends. 
Thanks,

**Comment by BigEdDev** [comment]
This has been amended, feel free to reopen if this has not solved the issue.
